version: "3.8"

services:

#  postgredb:
#    image: postgres
#    container_name: ostgresql_db
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_PASSWORD= Твоята парола дето е в джангото
#      - POSTGRES_USER= Юзъра дето е в джангото
#      - POSTGRES_DB= имаето на базата дето е в джангото
#      - PGDATA=/var/lib/postgresql/data/pgdata
#    volumes:
#      - ./:/postgresql:/var/lib/postgresql/data
#    networks:
#      - backend-network#    restart: on-failure

  redis:
    image: redis
    ports:
      - "6379:6379"
    restart: on-failure
    #    networks:
    #      - backend-network

#volumes:
#  postgresql:
#    name: postgresql
#
#networks:
#  backend-network:
#    name: backend-network